name: Luna IEMS – MVP Projektplan
description: Technischer Projektplan basierend auf Masterplan v1 (RAG, Simulation, Dashboards)
version: 1.0

milestones:
  - title: M1 – Infrastruktur & Dev-Setup
    due_on: +7d
    issues:
      - Infra: Compose & ENV Setup
      - Healthchecks aller Services
      - GitHub Actions CI mit Lint & Smoke-Test

  - title: M2 – Datenbank & Migrations
    due_on: +14d
    issues:
      - Alembic/SQL Migrations für Tables & Views
      - Seed Script mit Mockdaten
      - Makefile Targets für `seed` & `migrate`

  - title: M3 – KI & RAG Engine
    due_on: +21d
    issues:
      - Embedding-, Qdrant- und Tika-Services implementieren
      - Prompt Persona (prompts/luna.yml)
      - API /rag/ask Endpoint + Reindex Job

  - title: M4 – Ingest Pipeline
    due_on: +28d
    issues:
      - Upload & URL-Ingest
      - Chunking & Deduplication (sha256)
      - Worker Training Pipeline

  - title: M5 – Simulation Layer
    due_on: +35d
    issues:
      - Smart-Meter Simulation (Postgres + CSV optional)
      - Market Simulation
      - API /sim/run (admin-only)

  - title: M6 – Recommender & Feedback
    due_on: +42d
    issues:
      - Events API (view|click|like|ask)
      - Nightly Ranking Job
      - /recommend Endpoint

  - title: M7 – Frontends
    due_on: +49d
    issues:
      - Customer Dashboard (Q&A, Charts)
      - Admin Dashboard (Upload, Health)
      - Auth (JWT + API-Key)

  - title: M8 – Sicherheit & Tests
    due_on: +56d
    issues:
      - Upload Validation (Typ, Größe)
      - Rate Limits /rag/ask
      - CI E2E Tests (Smoke + Lint + Load)

  - title: M9 – Developer Experience
    due_on: +63d
    issues:
      - Makefile Targets (dev/test/smoke)
      - Logs & JSON-Formatierung
      - DX-Dokumentation im README
