name-template: "🚀 Luna IEMS v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
version-template: "$MAJOR.$MINOR.$PATCH"

categories:
  - title: "✨ Features"
    labels: [feature, enhancement]
  - title: "🐛 Fixes"
    labels: [fix, bug]
  - title: "🧩 Refactor / Internal"
    labels: [refactor, chore]
  - title: "🧪 Tests & CI"
    labels: [test, ci]
  - title: "📚 Documentation"
    labels: [docs]

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: "false"

template: |
  ## 🌙 Luna IEMS Release Notes

  $CHANGES

  ---
  🧾 **Generated:** $DATE  
  🧩 **Commit:** $COMMIT  
  💡 **Maintainer:** Monika Pichlhöfer  
  🔗 [Repository](https://github.com/Luna-iEMS/luna-dev) • [Releases](https://github.com/Luna-iEMS/luna-dev/releases)
