services:
  # =====================================================
  # 🧠 API – FastAPI Backend
  # =====================================================
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file: [.env]
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - .:/app
      - ./data:/data
      - ./logs:/logs
      - ./models:/models
      - ./ollama-data:/root/.ollama
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      tika:
        condition: service_healthy
      ollama:
        condition: service_healthy
    user: "${UID:-1000}:${GID:-1000}"
    command: >
      bash -c "
        echo '🚀 Initialisiere Luna IEMS ...';
        set -e;
        bash /app/scripts/start_migrations.sh;
        python -u scripts/startup.py || echo '⚠️ Startup-Skript beendet (nicht kritisch)';
        echo '✅ Starte FastAPI-Service ...';
        exec python -m uvicorn api.main:app --host 0.0.0.0 --port 8000 --log-level info --reload
      "
    healthcheck:
      test: ["CMD", "curl", "-fs", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s
    networks:
      - luna-net

  # =====================================================
  # 🗄️ Datenbank – PostgreSQL
  # =====================================================
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-luna}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - luna-net

  # =====================================================
  # 💾 Qdrant – Vektor-Datenbank
  # =====================================================
  qdrant:
    image: qdrant/qdrant:v1.11.0
    restart: unless-stopped
    ports:
      - "${QDRANT_HTTP:-6333}:6333"
      - "${QDRANT_GRPC:-6334}:6334"
    environment:
      QDRANT__STORAGE__SYNC_DISABLED: "true"
      QDRANT__STORAGE__WAL_CAPACITY_MB: "64"
      QDRANT__STORAGE__WAL_SEGMENT_SIZE_MB: "128"
      QDRANT__STORAGE__DISK_CACHE_MB: "4096"
      QDRANT__LOG_LEVEL: "INFO"
      QDRANT__SERVICE__API_KEY: ""
      QDRANT__STORAGE__SNAPSHOTS_PATH: "/qdrant/storage/snapshots"
    volumes:
      - qdrant_data:/qdrant/storage
      - ./models:/models:ro
    networks:
      - luna-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:6333/dashboard || exit 0"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 120s

  # =====================================================
  # 🧠 Ollama – LLM Runtime
  # =====================================================
  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "${OLLAMA_PORT:-11434}:11434"
    environment:
      OLLAMA_KEEP_ALIVE: "0"
      OLLAMA_NUM_PARALLEL: "4"
      REQUIRED_MODELS: "llama3.1:8b nomic-embed-text"
    volumes:
      - ./ollama-data:/root/.ollama
      - ./scripts/start_ollama.sh:/start_ollama.sh:ro
    entrypoint: ["/bin/sh", "/start_ollama.sh"]
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:11434/api/tags >/dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - luna-net

  # =====================================================
  # 📑 Apache Tika
  # =====================================================
  tika:
    image: logicalspark/docker-tikaserver:latest
    restart: always
    ports:
      - "${TIKA_PORT:-9998}:9998"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9998/tika"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - luna-net

  # =====================================================
  # ⚙️ Worker – Hintergrundprozesse
  # =====================================================
  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["tail", "-f", "/dev/null"]
    env_file: [.env]
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_healthy
      tika:
        condition: service_healthy
      ollama:
        condition: service_started
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./models:/models
      - ./ollama-data:/root/.ollama
    networks:
      - luna-net

  # =====================================================
  # 🔄 Weekly Updater – Wartungsjob
  # =====================================================
  updater:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ["bash", "/app/scripts/update_all.sh"]
    env_file: [.env]
    volumes:
      - .:/app
      - ./ollama-data:/root/.ollama
      - ./logs:/app/logs
    networks:
      - luna-net
    restart: "no"

# =====================================================
# 🔗 Netzwerke & Volumes
# =====================================================
networks:
  luna-net:
    driver: bridge

volumes:
  db_data:
  qdrant_data:
  ollama_data:
  models:
  logs:
  data:

