services:
  db:
    image: postgres:15
    container_name: luna-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luna
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 90s
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - luna-net

  qdrant:
    image: qdrant/qdrant:v1.11.0
    container_name: luna-qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 6333 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - luna-net

  minio:
    image: minio/minio
    container_name: luna-minio
    command: server /data --console-address ":9001"
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/minio/health/live || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - luna-net

  tika:
    image: apache/tika:2.9.0.0
    container_name: luna-tika
    restart: unless-stopped
    ports:
      - "9998:9998"
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9998 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 90s
    networks:
      - luna-net

  ollama:
    image: ollama/ollama:latest
    container_name: luna-ollama
    restart: unless-stopped
    environment:
      OLLAMA_HOST: "http://0.0.0.0:11434"
      OLLAMA_ORIGINS: "*"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 11434 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 120s
    networks:
      - luna-net

  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: luna-api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      qdrant:
        condition: service_started
      ollama:
        condition: service_started
      tika:
        condition: service_started
      minio:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: luna
      ADMIN_API_KEY: ${ADMIN_API_KEY:-admin123}
      QDRANT_HOST: qdrant
      QDRANT_HTTP: 6333
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
      TIKA_HOST: tika
      TIKA_PORT: 9998
      MINIO_HOST: minio
      MINIO_PORT: 9000
      DOCS_PATH: /data/docs-luna
    ports:
      - "8000:8000"
    working_dir: /app
    volumes:
      - ./api:/app
      - ./docs-luna:/home/mp/iems-luna/docs-luna 
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8000/docs || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 60s
    networks:
      - luna-net

  worker:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: luna-worker
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: luna
      MINIO_HOST: minio
      MINIO_PORT: 9000
      INTERVAL_SMARTMETER: 60
      INTERVAL_MARKET: 300
    command: ["python", "worker/launch_simulations.py"]
    networks:
      - luna-net

volumes:
  pgdata:
  qdrant_data:
  minio_data:
  ollama_data:

networks:
  luna-net:
    driver: bridge


