name: CI – Luna IEMS Smoke

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint check
        run: |
          python -m compileall api/ scripts/

      - name: Docker Compose Smoke
        run: |
          docker compose -f docker-compose.dev.yml up -d
          sleep 30
          curl -f http://localhost:8000/api/v1/system/info
          docker compose down
