# .github/workflows/release-drafter.yml
name: 📦 Release Drafter

on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🧭 Update Release Draft
        uses: release-drafter/release-drafter@v6
        with:
          config-name: .github/release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
